### ISSUE TITLE
Usability Testing Prototype

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#137]

**Comment by DominicHuntington** [comment]
Figma is a little interesting to try to get the dimensions to look right so its a bit zoomed in but the updated prototype link is on the deliverable links document. I am unsure as to why the link apparently didn't work for Greg last deliverable @jbryant-umaine

**Comment by DominicHuntington** [comment]
https://www.figma.com/proto/LdyxnAEEzSf4SwIrpqmg6Z/Mockup?node-id=30-4&starting-point-node-id=30%3A4&t=pEEhiOi2U7mjkcBP-1

**Comment by jbryant-umaine** [comment]
Looks good to me.
