### ISSUE TITLE
moving registration to front end

### ISSUE THREAD

**Issue by Cadecarr64** [COS420-Fall24/TeamA#142]
registration is currently on backend.

**Comment by jbryant-umaine** [comment]
@benmiller150 Since you have been familiarizing yourself with Firebase, please ensure that I have correctly moved login/registration to the client in commit #153

**Comment by benmiller150** [comment]
Code is clean and works well. The styling makes it easy to read and navigate. Secure using firebase. Error handling is done well with try/catch. Ready for Team Review. @jbryant-umaine
