### ISSUE TITLE
Technical Design Document

### ISSUE THREAD

**Issue by Cadecarr64** [COS420-Fall24/TeamA#145]
(20 points) Design document includes design class diagram (DCD) with types and attributes/functions of all classes and files, and a link to commentable (and preferably editable e.g. with Miro or other tool) version of the diagram

The DCD needs to represent the team’s app. If it doesn’t reasonably agree with the project’s current source code or doesn’t show how the design patterns will be used, -5 points each.

The DCD should show classes with their attributes, associations, and methods, and types, and functions and parameters, that fit your team’s  app i.e. user stories, use cases. The DCD should match/build on the names, types, etc and domain model. 

For every mistake or mismatch, deduct -2 points.

As an example for “matching”/corresponding to domain model for domain objects (*not* React components), see 

Example 1

[Design class diagram in two parts at end and design patterns](https://drive.google.com/file/d/1A4M-QHJj76po3aUXHrCSbE1JZI6-GsKj/view?usp=share_link)

([domain model that the above design class diagram was based on](https://drive.google.com/file/d/1MAeNDAurnh6iuD1ReyepaZBMFpMHb_2L/view?usp=share_link))

**Comment by jbryant-umaine** [comment]
This has been finished. @DominicHuntington can you qc?

https://docs.google.com/document/d/1YKuxLxGurmn1sxnMXktl0K7XQI-Vz-KU/edit

**Comment by DominicHuntington** [comment]
Looks great
