### ISSUE TITLE
Sprint Backlog (D5)

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#180]

**Comment by benmiller150** [comment]
@drewmarecek 
https://docs.google.com/spreadsheets/d/1TGVauFbj1rgfYudzX99NrMz1UYBTBatQ/edit?usp=sharing&ouid=115293949022024932489&rtpof=true&sd=true

**Comment by benmiller150** [comment]
Sprint Backlog 6  (/5)


The comments from Deliverable 5 must be addressed. 






For any comment that was not addressed, deduct -2 points. 






Contains only the stories (user stories and technical and non-technical stories) you commit to working on and delivering for Deliverable 5.  Should reflect the product backlog. That is, all the user stories that are assigned to Sprint 4 in the product backlog, should be shown in the Sprint Backlog 4.






For any missing user story, deduct -2 points.





If the Sprint Backlog 4 does not reflect the product backlog, deduct -5 points.
