### ISSUE TITLE
Address Project Story Feedback

### ISSUE THREAD

**Issue by jbryant-umaine** [COS420-Fall24/TeamA#20]
Based on the comments from deliverable 0.

If the comments were not addressed, the document will be marked as 0.

If the comments are partially addressed, the document will be marked as 2.5.

You must document a changelog by replying to the Google document comments when you think an issue has been addressed. You must also reply to comments saying what you didn’t address.

**Comment by benmiller150** [comment]
added a fix to one of the correction (other budgeting apps are paid products and “Findings indicate that while all apps support tracking of transactions, one third of the apps do not support budgeting informed by money envelopes” (link below) so without budgeting knowledge they arn’t very useful )
