### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by jbryant-umaine** [COS420-Fall24/TeamA#21]
Product backlog and sprint backlog should match i.e. product backlog items in the sprint backlog need to have the same IDs etc. If they do not match deduct -2 points.

Make sure that all of your user stories are in the product backlog. For any missing user story deduct -1 point.

All columns based on the projects’ details document should be in the product backlog and must be filled out. For any missing column or missing information deduct -2 points.
If using the "regularly export this from Github Projects" option, your Product Backlog items/user stories should have the user story field set to Yes so they show up in the Product Backlog view correctly.

**Comment by benmiller150** [comment]
https://1drv.ms/x/c/63fd447a58458636/EcQnD-giiVtEssPHcu-oEfgBOkMpIX5D7mMe-st-eFr-uw?e=faBJNj

**Comment by DominicHuntington** [comment]
Needs to have our user storys added to it and other information such as priority similar to this example 

https://docs.google.com/spreadsheets/d/14DN41vuV5kV_J6hwGp40sGkVDdGYiAt5/edit?gid=944386808#gid=944386808

It might be best to just make a copy of Gregs example included below as it includes their comments on some of the story point things 

https://docs.google.com/spreadsheets/d/1422Rr_2YRKFydVoz7m8bNor666bmfIwj/edit?gid=616909607#gid=616909607

**Comment by benmiller150** [comment]
https://1drv.ms/x/c/63fd447a58458636/EWz9I_bFe9lJlDTNmVe2GIcBGRr0cNjdJ9pfvbdgS8d4ag?e=u6uo7W


updated backlog

**Comment by benmiller150** [comment]
review : @DominicHuntington
