### ISSUE TITLE
Sprint Review

### ISSUE THREAD

**Issue by jbryant-umaine** [COS420-Fall24/TeamA#23]
Use the template as an agenda for the sprint review meeting. Step through each point as a team, have a discussion and have someone take notes. The team should review the notes during the meeting in a shared Google Doc to make sure everyone is heard, and anyone can edit the notes. 

This document is generally 1-2 pages. 

Should be written for this past sprint / week (i.e. for Deliverable 1, Deliverable 1 and Revisions for Deliverable 0)

Use the template as an agenda for the sprint review meeting. Step through each point as a team, have a discussion and have someone take notes. The team should review the notes during the meeting in a shared Google Doc to make sure everyone is heard, and anyone can edit the notes. 

For any missing item from the template, deduct 2 points.

Document should contain all prior Sprint Reviews as well, with the most recent at the top (the first sprint review happens in Deliverable 1). This is so you can read over the whole history of the project reviews and notice any patterns.

**Comment by Cadecarr64** [comment]
https://docs.google.com/document/d/1UF04dtffF-z9pm6NUZ1wvuLHAZjAbLLB/edit

sprint review document is used in sprint review to go over as team and fill out. i created the document and filled out the implemented features but we will need to go over the rest as a team

**Comment by Cadecarr64** [comment]
@jbryant-umaine ready for review

**Comment by jbryant-umaine** [comment]
@Cadecarr64 Overall good, but "How problems were solved" has a blank bulletin point:
![image](https://github.com/user-attachments/assets/a3d78370-e7b3-4b31-8193-29a40e5e38d2)

Additionally, I feel like a huge improvement could be to mention that our team should communicate over Discord more about what they are working on. It's sometimes hard to tell until we all meet at our scheduled times.
