### ISSUE TITLE
Software

### ISSUE THREAD

**Issue by jbryant-umaine** [COS420-Fall24/TeamA#24]
The implementation should have been started. 

If there is no code/HTML/scripts in Github, this part will be graded as 0.

Setting up the build environments and the necessary dependencies.  

You do not need to have any significant progress on developing your application. Focus on setting up the build environment.You can   use create-react-app or otherwise create your project structure.

Your README file should detail the installation and build process for your application. Make sure it works on each person’s machine.

Submit screenshot(s) or a single video showing the app running on each person’s machine 

If there is nothing, deduct -5 points.

**Comment by jbryant-umaine** [comment]
@drewmarecek for review:
I added a basic react layout using 'create-react-app'
Info about the tool can be found [here](https://create-react-app.dev/docs/getting-started).

**Comment by jbryant-umaine** [comment]
![Image](https://github.com/user-attachments/assets/ab9f90fc-3b7a-4690-9710-86bae915513a)

@COS420-Fall24/team-a  We are required to post a screenshot of the app running on everyone's machine. This can be done by git pulling the project, running `npm install` in the app directory, and then running `npm run start` in console.

**Comment by DominicHuntington** [comment]
Your README file should detail the installation and build process for your application.
