### ISSUE TITLE
SRS: 5 functional 3 nonfuntional

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#28]
Begin the requirements by selecting a few of the features that you would like to develop first  and write the requirements for them. Continue with the next features if you still need to have  more requirements. 

For each wrong requirement deduct -2 points. 

For each conflicting/contradictory requirement, deduct -2 points.

**Comment by DominicHuntington** [comment]
functional requirements 1-5 and non functional 5.1.1, 5.3.1 and 5.4.1.  Currently not assigned to anyone for review as I am unsure where people are at with their current tasks and don't want to overload anyone

**Comment by benmiller150** [comment]
https://1drv.ms/x/c/63fd447a58458636/EWz9I_bFe9lJlDTNmVe2GIcBGRr0cNjdJ9pfvbdgS8d4ag?e=u6uo7W


updated backlog
