### ISSUE TITLE
SRS: 3 Non-Functional requirements

### ISSUE THREAD

**Issue by Cadecarr64** [COS420-Fall24/TeamA#37]
Begin the requirements by selecting a few of the features that you would like to develop first  and write the requirements for them. Continue with the next features if you still need to have  more requirements. 

For each wrong requirement deduct -2 points. 

For each conflicting/contradictory requirement, deduct -2 points.

**Comment by Cadecarr64** [comment]
Non functional:
The software shall ask for permission to retrieve and display users location
The software shall only save user edits to profile when save button is clicked
The software shall display error message and return to home screen when an error is encountered

**Comment by DominicHuntington** [comment]
Looks good!
