### ISSUE TITLE
Maintain sprint backlog (D2)

### ISSUE THREAD

**Issue by Cadecarr64** [COS420-Fall24/TeamA#48]
https://docs.google.com/spreadsheets/d/1TGVauFbj1rgfYudzX99NrMz1UYBTBatQ/edit?gid=1448491115#gid=1448491115

maintain sprint backlog as needed

**Comment by Cadecarr64** [comment]
https://docs.google.com/spreadsheets/d/1TGVauFbj1rgfYudzX99NrMz1UYBTBatQ/edit?gid=1448491115#gid=1448491115

added story points completed and names and completion percentage

**Comment by Cadecarr64** [comment]
Sprint Backlog 2  (/2.5) 



Contains only the stories (user stories and technical and non-technical stories) you commit to working on and delivering for this Deliverable.  Should reflect the product backlog. That is, all the user stories that are assigned to this Sprint in the product backlog, should be shown in this Sprint Backlog.




For any missing user story, deduct -2 points.




If the Sprint Backlog 1 does not reflect the product backlog, deduct -5 points.





You must have other technical tasks in your backlog



You must have other tasks in the backlog, like documentation, requirements, UI mockups, etc. As covered in class sessions, these are called non-technical stories.

**Comment by greglnelson** [comment]
looks like this was not QC'd
