### ISSUE TITLE
Review SRS feedback

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#53]

**Comment by DominicHuntington** [comment]
https://docs.google.com/document/d/1PYV0Tka3aAg_P9QqBibWcu6nNdfGiyAy2U_UivyAw4E/edit?tab=t.0 I had somehow also assigned myself this task but you did great! I just made a changelog in case you hadn't and tried to summarize your changes but if you can word what you changed in the table better then that would be great. @drewmarecek

**Comment by drewmarecek** [comment]
I put all the changes I made in that doc, it should be all set now.
