### ISSUE TITLE
SRS Overall Description

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#54]

**Comment by benmiller150** [comment]
(rubric description+ links)

**Comment by benmiller150** [comment]
https://1drv.ms/w/c/63fd447a58458636/EW9DHEsE5XNNkucx6MrOim4BmgZs89EWhL0xwxBItSyh3w?e=DU3QrB

**Comment by benmiller150** [comment]
rubric link    https://courses.maine.edu/d2l/le/calendar/358652/event/1663685/detailsview#1663685
