### ISSUE TITLE
SRS Introduction

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#67]
example SRS https://docs.google.com/document/d/102TYJwTMRb3uJG8bkk1XLBtnxU4dJYYT/edit

**Comment by DominicHuntington** [comment]
Currently the application name is just "Blank" as I couldn't remember if we had a name for it yet or not. In the example SRS the introduction had some information on the programs used like Firebase but did not want to specify it myself being I could not remember all the details on what we were using.

Example:

https://docs.google.com/document/d/1WkqFkOZBiUtC19x8w7Zt7qIg8MJishZp/edit#heading=h.tyjcwt

Our SRS for review:

https://docs.google.com/document/d/15dX5PR8m7-ODKg8d_KtS-l_-5m1SdGBZ/edit

@jbryant-umaine Since you have the best understanding currently of what programs we are using for the application I am choosing you to do the review

**Comment by jbryant-umaine** [comment]
It looks good to me. I made an edit including the app's name (EmpowerMaine) along with abbreviations that will be used throughout the document. (5% work)
