### ISSUE TITLE
Sprint Backlog (D1 Revision)

### ISSUE THREAD

**Issue by jbryant-umaine** [COS420-Fall24/TeamA#68]

**Comment by DominicHuntington** [comment]
Please make sure to add feedback and how you addressed it to this Changelog 
https://docs.google.com/document/d/1PYV0Tka3aAg_P9QqBibWcu6nNdfGiyAy2U_UivyAw4E/edit?tab=t.0

**Comment by Cadecarr64** [comment]
https://docs.google.com/spreadsheets/d/1TGVauFbj1rgfYudzX99NrMz1UYBTBatQ/edit?gid=1448491115#gid=1448491115

added story points completed and names and completion percentage

**Comment by Cadecarr64** [comment]
Sprint Backlog 2  (/2.5) 



Contains only the stories (user stories and technical and non-technical stories) you commit to working on and delivering for this Deliverable.  Should reflect the product backlog. That is, all the user stories that are assigned to this Sprint in the product backlog, should be shown in this Sprint Backlog.




For any missing user story, deduct -2 points.




If the Sprint Backlog 1 does not reflect the product backlog, deduct -5 points.





You must have other technical tasks in your backlog



You must have other tasks in the backlog, like documentation, requirements, UI mockups, etc. As covered in class sessions, these are called non-technical stories.
