### ISSUE TITLE
Convert UI to figma (D3)

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#82]
Link to current prototype: 
https://www.figma.com/proto/LrX8YzZnd1W2rdeqTbe3e7/Figma-basics?node-id=1669-162202&t=AlShHJoZR5Ak9qVt-1

**Comment by jbryant-umaine** [comment]
Looks good to me. We could also combine job/mentor into a single listing page.

**Comment by DominicHuntington** [comment]
lets link this under usability testing when we submit the deliverable to show our current progress on it along with the script/forum I am filling out.
