### ISSUE TITLE
Make a login for the app (D3)

### ISSUE THREAD

**Issue by drewmarecek** [COS420-Fall24/TeamA#86]

**Comment by benmiller150** [comment]
@jbryant-umaine pushed it to the git

**Comment by jbryant-umaine** [comment]
@benmiller150 It looks like you pushed to "master" not "main" and I am unable to access your changes for some reason. Can you push to main or submit a pull request with your changes? Thanks.

**Comment by jbryant-umaine** [comment]
Ok, I see the model was updated to include a login function using Firebase.

You will also need to write a login controller similar to this:
https://github.com/COS420-Fall24/TeamA/blob/main/app/controller/register.js

and then point the route to it with a POST to `/login` (using the login controller) like this:

https://github.com/COS420-Fall24/TeamA/blob/main/app/routes/api.js#L6

**Comment by benmiller150** [comment]
created a new branch and created a pull request to main @jbryant-umaine

**Comment by jbryant-umaine** [comment]
@benmiller150 Your login implementation was how I expected it to work, but unfortunately, it did not work. Firebase is supposed to have the client login and then receive a token from the API. Then it would send it to the backend which it uses to fetch your user data. I just implemented this on the web app and now it should be fine.

Please review and test the changes on main.
