### ISSUE TITLE
Develop test cases for the app (D3)

### ISSUE THREAD

**Issue by drewmarecek** [COS420-Fall24/TeamA#87]

**Comment by jbryant-umaine** [comment]
I added jest to our application and added two tests for the registration component:

https://github.com/COS420-Fall24/TeamA/blob/main/app/client/register/Register.test.jsx

**Comment by jbryant-umaine** [comment]
@Cadecarr64 Please review the test cases for the app. I know we are missing some for Login right now, but we will implement that next deliverable.
