### ISSUE TITLE
Front end UI (D3)

### ISSUE THREAD

**Issue by DominicHuntington** [COS420-Fall24/TeamA#88]
If there is no HTML/CSS UI (this may include React components or just plain static HTML/CSS ) that looks similar to at least one of your UI mockups (or you have no UI mockups in your SRS, even if there is some UI), deduct -10 points

**Comment by jbryant-umaine** [comment]
Added a login UI to the app. It's not fully identical to the SRS but it's close.

@DominicHuntington Please review.

**Comment by DominicHuntington** [comment]
Looks great!
